### ISSUE TITLE
Setting to change to a darker interface

### ISSUE THREAD

**Issue by Burgo-admin** [Areso/1255-burgomaster#520]
“ For starters I think people would prefer a darker interface more :P And take use of all the screen space, there are a lot of empty white space currently” -Boohi 2021

**Comment by Voldus** [comment]
Dark UI theme requires minor updates, such as outline for treausry guard and font color fixes.

**Comment by Burgo-admin** [comment]
Still it’s not that hard and is possible

**Comment by Areso** [comment]
@Burgo-admin you could start with outlines, since you could draw, I will check the fonts

**Comment by Burgo-admin** [comment]
Change to grey or white?

**Comment by Burgo-admin** [comment]
What do you mean by that?

**Comment by Areso** [comment]
![image](https://user-images.githubusercontent.com/4927300/114615360-458c5780-9cae-11eb-872b-4bf90695f3bb.png)

**Comment by Burgo-admin** [comment]
Still not done?

**Comment by Areso** [comment]
It still has issues.
Do you the treasury guard?
But it is there :)

**Comment by Burgo-admin** [comment]
https://ibb.co/rt3tnBP

**Comment by Areso** [comment]
Kinda fixed in https://github.com/Areso/1255-burgomaster/commit/9fdca5e4cce0b7dd34f846a0fc3f76bdf94c80e8
If any bugs - report in new issues.
