### ISSUE TITLE
Adventure map 

### ISSUE THREAD

**Issue by Burgo-admin** [Areso/1255-burgomaster#540]
Adventure map lags hard on collecting item test this on apple (bug)

**Comment by Areso** [comment]
@Burgo-admin could you record your gameplay and put it on youtube?
I want to see the difference

**Comment by Burgo-admin** [comment]
https://youtu.be/rRVdMuEMrG0

**Comment by Areso** [comment]
Terrible experience. I need to admit, it works badly.

**Comment by Burgo-admin** [comment]
The log and timer doesn’t lag while but the adventure map is unplayable

**Comment by Areso** [comment]
Was it always like this or it was introduced in the last updates?
Or you don't know?

**Comment by Burgo-admin** [comment]
Recent update made it like that try going back an update as a test maybe?

**Comment by Areso** [comment]
try this one http://1255.mydiod.ga/

**Comment by Burgo-admin** [comment]
Doesn’t lag but seems like a different game

**Comment by Areso** [comment]
Fixed double-movements.
If it still lags, please make another one bug.
