### ISSUE TITLE
bug - Displaying username in game chat doesn't match real data

### ISSUE THREAD

**Issue by Persineya** [Areso/1255-burgomaster#725]
Environment: Google chrome (109.0.5414.120)

1. Chage user in settings tab
2. At the bottom of the screen change "log" to "chat"
3. Enter text, press send.

ER - the username must match in the box next to the input field with the name in the chat.
AR - the username does not match in the box next to the input field with the name in the chat.

![Screenshot_15](https://user-images.githubusercontent.com/122931944/215268487-ab37771a-4a84-48a8-9f77-632e62593405.png)

**Comment by batmanovnn** [comment]
The input field cannot be edited.
Test env's:
- **OS:** Linux Ubuntu__**Browser:** Mozila Firefox
- **OS:** Linux Ubuntu__**Browser:** Google Chrome
- **OS:** Android 9 ____**Browser:** Mozila Firefox (Mobile)
- **OS:** Android 9 ____**Browser:** Google Chrome (Mobile)

**Comment by Areso** [comment]
It shouldn't be.
Well, prolly I should change input type to label type.

**Comment by Areso** [comment]
converted the element.
could you check it out?

**Comment by Areso** [comment]
@Persineya

**Comment by batmanovnn** [comment]
Guest user don't have name in the chat.
![image](https://user-images.githubusercontent.com/48848918/217777516-7ab0ca78-4599-4281-9000-0514790aea94.png)

**Comment by Areso** [comment]
@Persineya @batmanovnn should be fixed by now, please confirm.

**Comment by batmanovnn** [comment]
Confirm it works

**Comment by Areso** [comment]
finally fixed
