### ISSUE TITLE
Game fails to export/cloud save if played in Russian

### ISSUE THREAD

**Issue by Areso** [Areso/1255-burgomaster#728]
1. Game fails to export/cloud save if played in Russian.
2. It fails while trying to BTOA game object.
3. Happens after the Inn built, when we generate the blackmarket goods in `genBlackMarketGoods`
4. Because addItem adds the objects to the game, instead of adding theirs ids.

**Comment by Areso** [comment]
eyJnb2xkIjo1NDIsImdlbXMiOjAsInBvcCI6ODIsInNlYXNvbiI6NCwieWVhciI6MTI2OSwiZm9vZCI6MjAsInRyZWFzdXJ5R3VhcmQiOjAsImJ1aWxkTGV2ZWxEIjozLCJidWlsZExldmVsSCI6NiwiYnVpbGRMZXZlbFRyZWFzdXJ5IjoxLCJidWlsZExldmVsR2FsbG93cyI6MCwiYnVpbGRMZXZlbEZvdW50YWluIjowLCJidWlsZExldmVsU3Rhc2giOjEsImJ1aWxkTGV2ZWxJbm4iOjAsImJ1aWxkTGV2ZWxTdGFibGUiOjEsImJ1aWxkTGV2ZWxBcmNoZXJ5IjoxLCJidWlsZExldmVsU21pdGgiOjAsImJ1aWxkTGV2ZWxVbml2ZXJzaXR5IjowLCJmaXJlIjowLCJmaXJlU3RlcHMiOjAsImZpcmVHdWFyZCI6MCwiaGVybyI6MCwiaGFwcGluZXNzIjo4MCwib19hdXRvc2F2ZSI6MCwibmV3U2F2ZVZlcnNpb24iOjgsInNhdmVWZXJzaW9uIjoic2F2ZVYxMDEwIiwiY2FzdGxlWCI6MSwiY2FzdGxlWSI6MSwiaGVyb1giOjEsImhlcm9ZIjoxLCJtYXBDcmVhdGVkIjowLCJteU1hcExhbmQiOltdLCJteU1hcE9iamVjdHMiOltdLCJteU1hcFJlbU9iamVjdHMiOltdLCJ5ZWFycyI6W10sInBvcHMiOltdLCJidWRnZXRzIjpbXSwiYWR2X3N0ZXBzIjowLCJhY19zdGVwcyI6MCwidXNlclBvcEFjayI6MCwidXNlckdvbGRBY2siOjAsInVzZXJBU2F2ZUFjayI6MCwiYmxhY2tNYXJrZXRHb29kcyI6W10sImlzSGVybyI6MCwiY2l0eVdhcmVob3VzZSI6W10sIm15aGVybyI6e30sIm15aGVyb0FybXkiOnsiYXJteUlEIjoxLCJ1bml0cyI6e319LCJjYXN0ZWxsYW4iOnt9LCJmZXN0aXZhbF9jb29sZG93biI6MCwic2VyZ2VhbnRzIjowLCJ0dXJrb3BvbHMiOjAsImtuaWdodHMiOjAsImFjdGl2ZV90YWIiOiIiLCJwcmVzdGlnZSI6MCwicHJlc3RpZ2VfdGltZSI6W10sImlzTW9iaWxlIjowLCJzZnhfYWxsIjowLCJzZnhfZXZlbnRzIjowLCJzZnhfYWN0aW9ucyI6MCwibXVzaWNfYWxsIjowLCJtdXNpY19zY3JpcHRzIjowLCJsb2dfc2l6ZSI6OCwiYWxpYXMiOiIiLCJVSUQiOiIxNjc1MDI0MzM2NTQwMjk2OTciLCJuaWNrbmFtZSI6Ikd1ZXN0MzI1NSIsInRpcHMiOlsidHV0b3JpYWwxX3BvcDAiLCJ0dXRvcmlhbF9kZWZlbnNlIiwidHV0b3JpYWxfdHJlYXN1cnkiLCJ0dXRvcmlhbF90cmVhc3VyeV9ndWFyZHMiLCJ0dXRvcmlhbF9uZXdfYnVpbGRpbmdzIiwidHV0b3JpYWxfYXV0b3NhdmUiLCJ0dXRvcmlhbF9zdGFzaCIsInR1dG9yaWFsX3N0YWJsZSIsInR1dG9yaWFsX2FyY2hlcnkiLCJ0dXRvcmlhbF9pbm4iXSwic3RvcnkiOltdLCJjaGVzdENpdHkiOjAsInRpY2tzIjo1OCwiYXV0b2NhbXBhaWduQ291bnRlciI6MCwiYXV0b2NhbXBhaWduQmF0dGxlc0NvdW50ZXIiOjAsImVuZW15SGVybyI6bnVsbCwiZW5lbXlIZXJvQXJteSI6eyJhcm15SUQiOjIsInVuaXRzIjp7fX0sImVuZW15TWF4QXJteUNvdW50IjozLCJleHBSZXdhcmQiOjAsImdvbGRSZXdhcmQiOjAsImRpZmZpY3VsdHlNb2RpZmllciI6MCwiYXR0YWNrZXIiOjEsImlzQXV0b0JhdHRsZSI6ZmFsc2UsImlzRGVmZWF0ZWQiOmZhbHNlLCJuaWdodE1vZGUiOmZhbHNlLCJtb25zdGVyc09uQWR2TWFwIjpbXSwidGVjaExlYXJuZWQiOltdLCJ0ZWNoRW5hYmxlZCI6W10sInRlY2hEaXNhYmxlZCI6W10sInRlY2hBcnRpbGxlcnkiOjAsInJvbGUiOiJwbGF5ZXIiLCJpc1R1dG9yaWFsU3RhdGUiOnRydWV9

savegame

**Comment by batmanovnn** [comment]
This problem is actual. 
Steps:
1) Clear cookies in browser
2) Open Game
3) Go to Settings -> login
4) Go to CIty -> 
AR: Button "load game" is not view on the City display 
5) Go to Settings -> press "Load save from Cloud"
AR: "01:09: you don't have savegame in the cloud"

Due to this problem, it will not work to restore the game in another browser (for example, on a phone).
