### ISSUE TITLE
The gallows cannot be taken down

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#739]
When playing for a long period of time, the game offers to change tactics and demolish the gallows in the city. A modal window appears with a suggestion. But the action doesn't happen.
**OS:** Linux Ubuntu  **Browser:** Mozilla Firefox
**server:**  prod

ER: After press button "Yes, demolish it" the gallows is must be demolish.
Steps to reproduce:

1. Build the city and build the gallows in it
2. Wait for a modal window with a message from the game (see picture)
3. Press the button "Yes, demolish it"

![Screenshot from 2023-02-08 00-48-02](https://user-images.githubusercontent.com/48848918/217461283-d4e8dbe0-5d5a-4da4-b43c-82cbe5987f34.png)

**Comment by Areso** [comment]
closed by https://github.com/Areso/1255-burgomaster/commit/a41031b036ab4c130b4347b24d7d49535f9bad5d
