### ISSUE TITLE
POST request (get_user_umber) have an avalanche growth

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#749]
After user authorization, each subsequent click of the login button adds at least 3 requests in the period between ticks (GET request event_countdown).

**env:** Linux Ubuntu 23 browser: Mozilla Firefox or Google Chrome
**stand:** test and prod

**Steps to reproduce:**

1. Go to the stand
2. Menu Settings -> authorization/registration form
3. Push button LOGIN (id="btnLogin")
4. Enter login and pass in form authorization
5. Push button Login (id="btnRegLogin")
6. log:  login successfull
The first click (3 get_user_umber)
![3](https://user-images.githubusercontent.com/48848918/218824895-1d0ca7ac-6ccc-40ad-9b04-ca7264e46071.png)
7.  Push button Login (id="btnRegLogin")
8.  log:  login successfull
The second click (6 get_user_umber)
![6](https://user-images.githubusercontent.com/48848918/218824926-6495590b-df95-43f8-a7c8-006898f78e17.png)
9. Push button Login (id="btnRegLogin")
10.  log:  login successfull
The third click (9 get_user_umber)
![9](https://user-images.githubusercontent.com/48848918/218824949-d9a00c5a-6a22-4677-a1fc-f492dc768d8d.png)
11. Push button Login (id="btnRegLogin")
12.  log:  login successfull
The fourth click (14 get_user_umber)
![14](https://user-images.githubusercontent.com/48848918/218824969-50af1773-0608-4abc-aaef-272f6037d41f.png)

After a successful user login need:
- hide login form
- change button text (id="btnLogin") to "Unlogin" or "Log out"
-  add test in function this button

**Comment by Areso** [comment]
There is a problem, that's login state is also presented on the backend.
And it could desync with a client (just an example, when backend is restarting in every morning), you would see the "log out" button, though in the server your session was eliminated by flushing the RAM.
The "avalanche" problem looks good, will look into it, but not today.

**Comment by Areso** [comment]
Fix should be rolled out to the test server.
