### ISSUE TITLE
Typo in message

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#750]
Need change message "login successfull" -> "Login successful"

**Comment by Areso** [comment]
it's a policy.
So far, after timestamp everywhere all lines starts with a small letter.

**Comment by batmanovnn** [comment]
Typo in extra last "l"

**Comment by batmanovnn** [comment]
> it's a policy. So far, after timestamp everywhere all lines starts with a small letter.

Typo in extra last "l"
