### ISSUE TITLE
The senting is empty requests (register_user)

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#751]
The POST request (register_user) is sent even if the registration form is empty.

**env:** Linux Ubuntu 23 **browser:** Mozilla Firefox or Google Chrome
**stand:** test and prod

**Steps to reproduce:**

1.     Go to the stand
2.     Menu Settings -> authorization/registration form
3.     Push button REG (id="btnReg")
4.     Fields Nickname, Password and Email in the registration form are empty
![Screenshot from 2023-02-16 00-16-06](https://user-images.githubusercontent.com/48848918/219108838-da88d251-263a-426a-ba7e-1cfb287719f5.png)

5.     Push button Login (id="btnRegLogin")

**ER:** Error message. The request is not send.
**AR: **The request with empty fields send to server. And Received a response from the server (400)
![Screenshot from 2023-02-16 00-15-52](https://user-images.githubusercontent.com/48848918/219109169-b3f72e49-00a3-49c4-b5ef-2adf544508e1.png)
![Screenshot from 2023-02-16 00-39-38](https://user-images.githubusercontent.com/48848918/219109304-bb0acc6b-1b80-4053-b8a5-b99191432364.png)

**Comment by Areso** [comment]
should be fixed at test server.
