### ISSUE TITLE
Game trying import game for non-logged in user

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#756]
**env:** Linux Ubuntu 23 **browser:** Mozilla Firefox or Google Chrome
**stand:** test and prod

**Steps to reproduce:**
1. as a non-logged in visitor, access homepage: https://test.1255.areso.pro/
2. Go to Settings tab
3. on Newsletter field, enter a valid email address
4. click on "Import Game"

**AR:** The state of the playing field has not changed
**log:** game loaded successfully
**browser log**:
![Screenshot from 2023-02-21 01-41-12](https://user-images.githubusercontent.com/48848918/220179953-6e58a50b-a812-4952-abb8-f1401c883288.png)

**ER:** log message: "Please login as a user, then you can load your saved game"

**Comment by Areso** [comment]
Import game is available, when you have exported game pasted in the text field.
Export and Import aren't tied to online features

**Comment by batmanovnn** [comment]
[Screencast from 2023-02-21 02-02-03.webm](https://user-images.githubusercontent.com/48848918/220182473-41af1bd9-0e8f-44f8-856c-8458a6def348.webm)

**Comment by Areso** [comment]
Loaded sucessfully, it seems, as I described.

**Comment by batmanovnn** [comment]
I'm sorry! I messed up the files.
