### ISSUE TITLE
Import sends empty error message to log

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#757]
**env:** Linux Ubuntu 23 **browser:** Mozilla Firefox or Google Chrome and Yandex Browser
**stand:** test and prod

**Steps to reproduce:**
1. access homepage: https://test.1255.areso.pro/
2. Go to Settings tab
3. on Import field, enter non-valid text
4. click on "Import Game"

**AR:** **log message:** placeholder
![Screenshot from 2023-02-21 02-15-42](https://user-images.githubusercontent.com/48848918/220185150-cb1f21df-a59c-4281-8206-aff8d0f2ee59.png)

**Comment by Areso** [comment]
@batmanovnn I can't reproduce it on https://test.1255.areso.pro/ environment (assuming, it's opened in private mode)

**Comment by batmanovnn** [comment]
@Areso No, no private mode when testing a product. Even Yandex browser wrote to log: "placeholder".
