### ISSUE TITLE
 The "Settings" tab not working

### ISSUE THREAD

**Issue by batmanovnn** [Areso/1255-burgomaster#766]
The "Settings" tab not responding to click

**env:** Linux Ubuntu 23 **browser:** Mozilla Firefox or Google Chrome
**stand:** test and prod

**Steps to reproduce:**
1.     Go to the stand
2.     Click on menu-button "Settings"

**EX:** Switching to the Settings tab
**AR:** No reaction.

**Comment by Areso** [comment]
Confirmed, a major bug.
